title: Fariz Hassan
logo: /assets/img/myphoto.gif
#description: a Malaysian
#show_downloads: true
resume_url: /assets/files/resume.pdf
theme: jekyll-theme-minimal
<a href="{{ site.resume_url }}" download="resume.pdf">Click Here to Download my Resume</a>
